#!/bin/sh
# Setup installation script
mkdir -p "$HOME/.config/kreato"
SCRIPT_DIR="$(dirname -- "$( readlink -f -- "$0"; )";)"
echo "$(realpath $SCRIPT_DIR/..)" > "$HOME/.config/kreato/setupdir"
cd "$(realpath $SCRIPT_DIR/..)"
ansible-playbook --ask-become-pass bootstrap.yml
